name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      - uses: actions/checkout@v3

      - name: run vitest
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: build
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm run ci